# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='archive',
            field=models.CharField(default='temp', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urls',
            name='timestamp',
            field=models.DateTimeField(default=1337),
            preserve_default=False,
        ),
    ]
