# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20160813_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='archive',
            new_name='wayback',
        ),
    ]
